services:


  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ollama --version || exit 1
      interval: 5s
    ports: 
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu


  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: langchain
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    profiles:
      - rag


  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag2
    healthcheck:
      test: pg_isready -U postgres -d rag2
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 6024:5432
    volumes:
      - local_pgdata2:/var/lib/postgresql/data
    profiles:
      - rag


volumes:
  local_pgdata2:
  pgadmin-data:
  ollama:
  open-webui: