x-shared-bits:
  ollama-common: &ollama-common
    image: ollama/ollama
    healthcheck:
      test: ollama --version || exit 1
      interval: 5s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


services:

  ollama-embeddings:
    <<: *ollama-common
    ports:
      - 11435:11434
    volumes:
      - ollama-embeddings:/root/.ollama
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: langchain
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag
    healthcheck:
      test: pg_isready -U postgres -d rag
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 6024:5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data



volumes:
  local_pgdata:
  ollama-embeddings:
  pgadmin-data: